---
- name: 'get-version : register version'
  shell: |
    /root/bin/get-version
  register: get_version

- name: 'get-version : add version to facts'
  ansible.builtin.set_fact:
    vm_version: '{{ get_version.stdout }}'

- name: 'get-version : store version in student directory'
  ansible.builtin.copy:
    dest: /home/student/.version
    content: |
      {{ vm_version }}
    mode: 0644
  become_user: student

